[package]
name = "mqtt_ping_pong"
version = "0.1.0"
authors = ["Emmanuel Bosquet <bjokac@gmail.com>"]
edition = "2018"

[[bin]]
path = "src/sync_ping.rs"
name = "sync_ping"

[[bin]]
path = "src/sync_pong.rs"
name = "sync_pong"

[dependencies]
paho-mqtt = "0.6.0"
